### ISSUE TITLE
Is it possible to use this with OpenGL versions < 3.2?

### ISSUE THREAD

**Issue by icefoxen** [alexheretic/gfx-glyph#16] opened 2018-02-05 15:20 UTC
Looking at using this for ggez again; while ggez has a nominal minimum of OpenGL 3.2, it would be nice if core features don't make it impossible to use versions lower than that.  Is OpenGL 3.2 a hard requirement?

**Comment by Xaeroxe** [comment] 2018-02-05 15:28
3.2 is now a 9 year old specification, resulting in little demand for anything lower.  IMO future development shouldn't be targeting anything lower, and in fact going forward I'd like an emphasis on newer graphics APIs, which hopefully will be achieved by a move to gfx-hal.

**Comment by alexheretic** [comment] 2018-02-05 15:32
I had used shader version 130 to support OpenGL 3.0 and up. However, this caused some issues for people on mac _(ie it didn't work as intended)_. I ended up deciding it was better to simply only support 3.2 to fix those core/compat issues, based on the fact that no-one seemed to actually need 3.0 & 3.1 support.

I basically only changed the shader versions of my glsl files 4662aa1b8150a2b24368516e008a0d224f87e851. 

It would be feasible to have an option to select OpenGL version, allowing 3.2 and later to be noop. 3.0 & 3.1 to change the version of the shaders before use. However this would add some API weight & I'm not totally sure the use case really exists.

**Comment by icefoxen** [comment] 2018-02-05 19:27
I totally sympathize but people still bitch from time to time, and probably will until the heat-death of the universe finally takes every pre-HD Intel laptop to the grave with it.  Ah well, was just curious.  3.2 is probably the best sane minimum, until we can just use gfx-hal instead.  😁

**Comment by alexheretic** [comment] 2018-02-05 20:39
I think this is something we _can_ technically support. This issue is we need a use case so we can test having the shaders at 130 actually helps anyone's setup.

It'll be easy enough to confirm if we find a test setup, just change the shader version to 130 and retry. If we get confirmation that this fixes the lib for some people I can probably add an optional `consider_info(gfx_device_gl::Info)`, _or similar_,to the builder to support this.

Until then I'll close this.

**Closed by alexheretic** 2018-02-05 20:39 UTC
